# Generated by Django 3.2.5 on 2021-07-01 14:25

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='name',
            field=models.CharField(default=music.models.get_file_name, max_length=255),
        ),
    ]
