# Generated by Django 3.2.5 on 2021-07-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
