# Generated by Django 3.2.5 on 2021-07-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='name',
        ),
    ]
